export const ProjectsData = [
  {
    title: '',
    tag: "",
    desc: "",
    deploy: '',
    github: '',
    mockup: '',
    tech: [
      '',
      '',
      ''
    ],
    photo: '',
    photoAlt: 'Landing page of ',
    gif: '',
    gifAlt: 'Brief demo of ',
  },
  {
    title: 'Space MUD',
    tag: "A randomly generated multi-user dungeon experience set in an abandoned spacecraft.",
    desc: "A one week project built by myself and four other developers. The Django framework was utilized to generate and serve a map, as well as provide additional endpoints for player interaction within the game.",
    deploy: 'https://vibrant-noyce-dc1ddd.netlify.com/',
    github: 'https://github.com/CSBeastMode',
    mockup: '',
    tech: [
      'React',
      'Terminal-in-React',
      'Styled-Components',
      'Python',
      'Django',
      'Pusher'
    ],
    photo: '',
    photoAlt: 'Landing page of Space MUD',
    gif: '',
    gifAlt: 'Brief demo of Space MUD',
  },
  {
    title: 'Appraiser BFF',
    tag: "Web app designed to assist in the valuation of a homeowner's property.",
    desc: "The goal of this project was to provide an estimated valuation of a homeowner's property determined by select features, with calculations based on existing aggregated data. As the backend developer, I created a RESTful API that handled user registration and login, property listings, as well as retrieved the calculated price that is returned from the data science model.",
    deploy: 'http://www.appraiserbff.xyz/',
    github: 'https://github.com/bw-appraisers-bff',
    mockup: '',
    tech: [
      'React',
      'React-Redux',
      'Node',
      'Express',
      'Bcrypt.js',
      'JSON Web Token',
      'Knex.js',
      'Supertest',
    ],
    photo: '',
    photoAlt: 'Landing page of Appraiser BFF',
    gif: 'https://www.loom.com/embed/470af25eea864b0ea7a566d9ac9c937c',
    gifAlt: 'Brief demo of Appraiser BFF',
  },
]